name: Deploy Node.js App with Docker

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          docker build -t my-node-app .

      - name: Login to DockerHub (optional)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to DockerHub
        run: |
          docker tag my-node-app myusername/my-node-app:latest
          docker push myusername/my-node-app:latest

      - name: Deploy the app
        run: |
          # Commands to deploy your application, e.g., SSH into a server
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} user@your-server-ip 'docker pull myusername/my-node-app:latest && docker run -d -p 3000:3000 myusername/my-node-app:latest'
