name: Docker Build and Deploy

on:
  push:
    branches:
      - main  # Trigger this on changes to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-docker-app:${GITHUB_SHA} .

      - name: Stop and Remove Old Container
        run: |
          container_id=$(docker ps -aq -f name=my-app-container)
          if [ -n "$container_id" ]; then
            echo "Stopping and removing container: $container_id"
            docker stop my-app-container || true
            docker rm my-app-container || true
          else
            echo "No container named 'my-app-container' found. Skipping stop and remove."
          fi

      - name: Run New Docker Container
        run: |
          docker run -d -p 3000:3000 --name my-app-container my-docker-app:${GITHUB_SHA}

